language: bash

env:
  matrix:
  - KUBECTL_VERSION=v1.15.0 NODE_VERSION=v1.15.0
  - KUBECTL_VERSION=v1.14.0 NODE_VERSION=v1.14.0
  - KUBECTL_VERSION=v1.13.0 NODE_VERSION=v1.13.3

services:
- docker

before_script:
# Download and install kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download and install kind
- curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/0.2.1/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
# Create a new kubernetes cluster
- kind create cluster --image="kindest/node:${NODE_VERSION}"
# Set KUBECONFIG environment variable
- export KUBECONFIG="$(kind get kubeconfig-path)"
# Show version
- kubectl version

script:
- make test

matrix:
  include:
  - &bash
    language: bash
    go: null
    env: null
    before_script: null
    script:
    - ./scripts/verify-authors.sh
  - <<: *bash
    script:
    - make lint
  - <<: *bash
    script:
    - make image
